version: "3.2"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_DATABASE: movies
      MYSQL_ROOT_PASSWORD: ahmed
    volumes:
      - sqlvolume:/var/lib/mysql


  laravel:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8881:8000
    restart: always
    volumes:
      - ./:/var/www/html

    command: bash -c "composer install
      && php artisan migrate
      && cp ./movies-cron /etc/cron.d/movies-cron
      && chmod 0644 /etc/cron.d/movies-cron
      && crontab /etc/cron.d/movies-cron && cron
      && php artisan serve --host=0.0.0.0 --port=8000 --no-ansi"



  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - 8883:80
      restart: always
      links:
        - mysql
      depends_on:
        - mysql
      environment:
          PMA_HOST: mysql
          PMA_ARBITRARY: 1
      volumes:
        - /sessions


volumes:
  sqlvolume:
